CREATE DATABASE IF NOT EXISTS todo;

CREATE TABLE IF NOT EXISTS TODO (
  id        INT(6) UNSIGNED       AUTO_INCREMENT PRIMARY KEY,
  title     VARCHAR(200) NOT NULL,
  completed BOOLEAN      NOT NULL DEFAULT FALSE
);